name: ci-build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  playwright:
    name: Playwright tests on ${{ matrix.browser }}
    strategy:
      fail-fast: true
      matrix:
        browser: [chrome, firefox, webkit]
    runs-on: windows-latest        
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - run: npm install
      - run: npm run setup
      - run: npm run test:${{ matrix.browser }}
        env:
          STANDARD: ${{ secrets.STANDARD }}
          PASSWORD: ${{ secrets.PASSWORD }}
      - name: reports
        uses: dorny/test-reporter@main
        if: success() || failure()
        with:
          name: Json reports
          reporter: 'mocha-json'
          path: 'output/*.json'
