name: ci-build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  chromeHeadLess:
    name: Chrome Headless
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 16.x
      - run: npm install
      - run: npm run setup
      - run: npm run test
